Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2018-03, with the labels that each got.

#31 grid-alignemnt: add new alignment options
  src/styles/grid/index.css
Labels: enhancement

#40 Add table aggregation row
  .circleci/config.yml
  src/styles/table/body.css
  src/styles/table/footer.css
  src/styles/table/index.css
  src/styles/table/properties.css
Labels: enhancement

#46 input: refactor style
  src/styles/form-fields/input/index.css
  src/styles/form-fields/input/properties.css
  src/styles/form-fields/properties.css
  src/styles/input/index.css
  src/styles/input/properties.css
Labels: devs, review-needed

#55 segmented-switch: refactor style
  src/styles/segmented-switch/index.css
  src/styles/segmented-switch/properties.css
Labels: devs, review-needed

#53 input: remove undefined variables
  src/styles/form-fields/input/properties.css
  src/styles/input/index.css
  yarn.lock
Labels: bug-fix, devs, review-needed

#54 chore: remove undefined variables
  src/styles/alert/index.css
  src/styles/form-fields/properties.css
  src/styles/segmented-switch/properties.css
Labels: bug-fix, devs, review-needed

#48 dropdown: refactor style
  src/styles/dropdown/index.css
  src/styles/dropdown/properties.css
  src/styles/form-fields/dropdown/index.css
  src/styles/form-fields/dropdown/properties.css
  src/styles/form-fields/properties.css
Labels: devs, review-needed
