Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2018-09, with the labels that each got.

#123 popover-content: refactor popover style
  src/styles/popover/index.css
  src/styles/popover/properties.css
Labels: devs, review-needed

#134 Revert "popover-content: refactor popover style"
  src/styles/popover/index.css
  src/styles/popover/properties.css
Labels: devs, review-needed

#133 alert: add base dark
  src/styles/alert/index.css
  src/styles/alert/properties.css
Labels: devs

#132 landing: refactor base
  src/styles/landing/index.css
  src/styles/landing/properties.css
Labels: devs, review-needed

#136 input: add base dark
  src/styles/form-fields/input/index.css
  src/styles/form-fields/properties.css
  src/styles/input/index.css
  src/styles/input/properties.css
Labels: devs, review-needed

#115 flexbox: add component styles
  src/styles/flexbox/index.css
  src/styles/index.js
Labels: devs, review-needed

#135 button: add ripple effect to button
  src/styles/button/index.css
  src/styles/button/properties.css
Labels: devs, review-needed

#137 Modal - Fix vertical alignment
  src/styles/modal/index.css
  src/styles/modal/properties.css
Labels: bug-fix, devs, review-needed

#138 chore: update former-kit version to 0.10.0
  package.json
Labels: devs, review-needed
