Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2019-04, with the labels that each got.

#169 sidebar: refactor sidebar min-width
  src/styles/sidebar/index.css
  src/styles/sidebar/properties.css
Labels: bug-fix, devs, review-needed

#170 button: add spinner loader
  src/styles/button/index.css
Labels: devs, review-needed

#172 release 1.2.0
  package.json
Labels: bug-fix, cos:standard, devs, review-needed

#166 truncate: add style component
  package.json
  src/styles/index.js
  src/styles/truncate/index.css
Labels: cos:standard, devs, review-needed

#173 Update version
  .stylelintrc
  package.json
  yarn.lock
Labels: cos:standard, devs, review-needed
