Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2019-02, with the labels that each got.

#158 Update to version 1.0
  package.json
Labels: cos:standard, devs, review-needed

#159 sidebar: add transition
  src/styles/sidebar/index.css
  src/styles/sidebar/properties.css
  src/styles/sidebar/sidebar-link.css
Labels: devs, review-needed, uxs

#161 snackbar: add style
  src/styles/index.js
  src/styles/snackbar/index.css
  src/styles/snackbar/properties.css
Labels: review-needed

#165 update version to 1.1.0
  package.json
  yarn.lock
Labels: cos:standard, devs, review-needed
