Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2019-07, with the labels that each got.

#188 release 1.3.3
  package.json
Labels: bug-fix, cos:standard

#186 SegmentedSwitch - Add styling for low relevance and tiny spacing
  src/styles/segmented-switch/properties.css
  src/styles/segmented-switch/spaced/index.css
Labels: devs, review-needed

#189 Update version
  package.json
Labels: cos:standard, devs, review-needed

#191 bump version to 1.3.5
  package.json
Labels: cos:standard, review-needed
