Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2019-09, with the labels that each got.

#194 Update font family
  src/styles/button/properties.css
  src/styles/card/index.css
  src/styles/card/properties.css
  src/styles/colors/light.css
  src/styles/date-input/properties.css
  src/styles/date-selector/properties.css
  src/styles/form-fields/dropdown/properties.css
  src/styles/form-fields/input/properties.css
  src/styles/form-fields/properties.css
  src/styles/header/properties.css
  src/styles/input/properties.css
  src/styles/layout/index.css
  src/styles/layout/properties.css
  src/styles/linear-progress/index.css
  src/styles/modal/index.css
  src/styles/modal/properties.css
  src/styles/pagination/index.css
  src/styles/pagination/properties.css
  src/styles/popover/properties.css
  src/styles/react-dates/properties.css
  src/styles/segmented-switch/index.css
  src/styles/segmented-switch/properties.css
  src/styles/segmented-switch/spaced/index.css
  src/styles/steps/properties.css
  src/styles/tab-bar/properties.css
  src/styles/table/properties.css
  src/styles/tag/properties.css
  src/styles/typography.css
  src/styles/webfonts/assistant/assistant-bold.woff
  src/styles/webfonts/assistant/assistant-bold.woff2
  src/styles/webfonts/assistant/assistant-regular.woff
  src/styles/webfonts/assistant/assistant-regular.woff2
  src/styles/webfonts/assistant/index.css
  src/styles/webfonts/rubik/index.css
  src/styles/webfonts/rubik/rubik-light.ttf
  src/styles/webfonts/rubik/rubik-medium.ttf
  src/styles/webfonts/rubik/rubik-regular.ttf
Labels: cos:standard, devs, review-needed

#201 bump eslint related dependencies
  package.json
  yarn.lock
Labels: cos:intangible

#202 bump react related dependencies
  package.json
  yarn.lock
Labels: cos:standard, review-needed

#204 bump version to 1.5.0
  package.json
Labels: cos:standard, devs, review-needed

#205 spaced-seg-switch: refactor font-size
  src/styles/segmented-switch/properties.css
Labels: devs, review-needed
