Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2019-10, with the labels that each got.

#207 font: refactor font-weight and add new color
  src/styles/colors/light.css
  src/styles/webfonts/rubik/index.css
Labels: bug-fix, cos:standard, devs

#210 chore: bump version to 1.5.1
  package.json
Labels: cos:standard, devs

#211 modal-actions: refactor margin-left in first-child
  src/styles/modal/index.css
Labels: cos:intangible, devs

#213 chore: bump version to 1.5.2
  package.json
Labels: cos:standard, devs, review-needed
