Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2020-02, with the labels that each got.

#223 Add/progress bar
  src/styles/colors/light.css
  src/styles/index.js
  src/styles/linear-progress/index.css
  src/styles/linear-progress/secondary-linear-progress/index.css
  src/styles/webfonts/roboto/index.css
  src/styles/webfonts/roboto/roboto-bold.ttf
  src/styles/webfonts/roboto/roboto-light.ttf
  src/styles/webfonts/roboto/roboto-medium.ttf
  src/styles/webfonts/roboto/roboto-regular.ttf
Labels: feature, review-needed

#225 release 1.6.0
  package.json
Labels: cos:standard, devs

#226 Add new color palette
  src/styles/colors/light.css
Labels: cos:standard, devs, feature, help-wanted, review-needed
