Repository pagarme/former-kit-skin-pagarme, pull requests merged in 2020-03, with the labels that each got.

#229 Adiciona tamanho mobile no componente Modal - skin
  src/styles/modal/index.css
  src/styles/modal/properties.css
Labels: devs

#231 release 1.7.0
  package.json
Labels: cos:standard

#228 button: add secondary button variant
  src/styles/button/default/index.css
  src/styles/button/default/properties.css
  src/styles/button/properties.css
  src/styles/button/secondary-button/index.css
  src/styles/button/secondary-button/properties.css
  src/styles/index.js
Labels: cos:standard, devs, feature

#233 dropdown: add SecondaryDropdown
  src/icons/form-fields/secondary-dropdown/index.js
  src/icons/index.js
  src/styles/form-fields/secondary-dropdown/index.css
  src/styles/form-fields/secondary-dropdown/properties.css
  src/styles/index.js
Labels: cos:standard, devs, help-wanted, review-needed

#234 chore: bump version to 1.8.0
  package.json
Labels: cos:standard
